version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./mongo-volume:/data/db
    working_dir: /data/db
    networks:
      - server
  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo_express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGODB_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGODB_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - '8081:8081'
    depends_on:
      - mongodb
    networks:
      - server

  server:
    container_name: server
    depends_on:
      - mongodb
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    networks:
      - server
  front:
    container_name: front
    depends_on:
      - mongodb
    build: ./Front
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $REACT_PORT:$REACT_PORT
    stdin_open: true
    tty: true
    networks:
      - front


volumes:
  db:

networks:
  server:
    driver: bridge
  front:
    driver: bridge
