version: "3.8"

services:
  mongodb:
    # on utilise l'image 5.0.2 de mongo
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    container_name: mongodb
    # variable d'environment pour setup mongo 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    #on crée un volume pour stocker les données de mongo, pour stocker de maniere persitance 
    volumes:
      - ./mongo-volume:/data/db
    working_dir: /data/db
    networks:
      - server
  mongo-express:
    # on utilise la derniere version disponible de mongo-express
    image: mongo-express:latest
    restart: always
    container_name: mongo_express
    # variable d'environment pour permettre de confirgurer l'acces de mongo-express à mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGODB_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGODB_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - '$MONGODB_EXPRESS_PORT:$MONGODB_EXPRESS_PORT'
    depends_on:
      - mongodb
    networks:
      - server

  server:
    container_name: server
    depends_on:
      - mongodb
    #on build le server avec le dockerfile du dossier server
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    # variable d'environment pour permettre de confirgurer l'acces du server à mongo
    environment:
      - UID=&UID
      - GUD=&GUD
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    cap_drop:
      - ALL
    networks:
      - server
  front:
    container_name: front
    depends_on:
      - mongodb
    #on build le server avec le dockerfile du dossier Front
    build: ./Front
    restart: unless-stopped
    env_file: ./.env
    environment:
      - UID=&UID
      - GUD=&GUD
    ports:
      - $REACT_PORT:$REACT_PORT
    stdin_open: true
    tty: true
    cap_drop:
      - ALL
    networks:
      - front


volumes:
  db:

networks:
  server:
    driver: bridge
  front:
    driver: bridge
