version: "3.8"

services:
  mongodb:
    # on utilise l'image 5.0.2 de mongo
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    container_name: mongodb
    # variable d'environment pour setup mongo 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./mongo-volume:/data/db
    working_dir: /data/db
    networks:
      - server
      
  server:
    container_name: server
    depends_on:
      - mongodb
    #on build le server avec le dockerfile du dossier server
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    # variable d'environment pour permettre de confirgurer l'acces du server à mongo
    environment:
      - UID=&UID
      - GUD=&GUD
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    cap_drop:
      - ALL
    networks:
      - server
  front:
    container_name: front
    depends_on:
      - mongodb
    #on build le server avec le dockerfile du dossier Front
    build: ./Front
    restart: unless-stopped
    env_file: ./.env
    environment:
      - UID=&UID
      - GUD=&GUD
    ports:
      - $REACT_PORT:$REACT_PORT
    stdin_open: true
    tty: true
    cap_drop:
      - ALL
    networks:
      - front
  vault:
      image: vault:latest
      environment:
        - VAULT_DEV_ROOT_TOKEN_ID=root_token
      ports:
        - "8200:8200"
volumes:
  db:

networks:
  server:
    driver: bridge
  front:
    driver: bridge
